# version: '3'
services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER_UID=${UID}
        - USER_GID=${GID}
    user: "${UID}:${GID}"
    container_name: my_front # コンテナ名を指定
    volumes:
      - ./public:/react/public
      - ./shellscript_linux:/react/shellscript_linux
      - ./src:/react/src
      - ./package.json:/react/package.json
      - ./yarn.lock:/react/yarn.lock
      - ./node_modules:/react/node_modules
    environment:
      USER_UID: ${UID}
      USER_GID: ${GID}
    ports:
      - "3000:3000"
    tty: true
    networks:
      - nakayama_network
    # フロントエンド（Reactなど）の開発・ビルド・配信を担当
    # ユーザーインターフェースを提供し、APIサーバーと通信する

  db:
    image: postgres:17-bookworm
    ports:
      - "3002:5432" # PostgreSQL のデフォルトポートは 5432
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'my_database' # 初期データベース名
    volumes:
      - postgres_data:/var/lib/postgresql/data # 起動の度にボリュームが作成されるのをを防ぐのためのボリューム
      - ./init-scripts:/docker-entrypoint-initdb.d/ # 初期化スクリプトをマウント
    networks:
      - nakayama_network
    # データベース（PostgreSQL）
    # アプリケーション層やAPIサーバーからのデータ保存・取得を担当

  nginx:
    image: nginx:1.27.5-bookworm
    ports:
      - 8000:8000
    networks:
      - nakayama_network
    # Webサーバー・リバースプロキシ
    # 外部からのリクエストをフロントやAPIサーバーに振り分ける
    # 静的ファイルの配信やロードバランシングも可能

  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    container_name: my_express
    volumes:
      - ./express:/app
    ports:
      - "4000:4000"
    networks:
      - nakayama_network
    environment:
      - DATABASE_URL=postgres://user:postgres@db:5432/my_database
    # アプリケーション層（APIサーバー、Express）
    # ビジネスロジックやデータベースとのやりとり、APIエンドポイントを提供
    # フロントエンドからのリクエストを処理し、必要に応じてDBと連携

volumes:
  postgres_data:


networks:  # ネットワークの定義
  nakayama_network:  # ネットワーク名
    driver: bridge  # ドライバの指定