name: Push Complete Notification

on:
  push:
    branches:
      - develop  # 監視するブランチを指定（例: main）

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # タイムゾーンを日本時間に設定
      - name: Set timezone to JST
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # プッシュ完了メッセージを表示
      - name: Display push complete message
        run: echo "プッシュ完了：$(date '+%Y-%m-%d %H:%M:%S')"